exclude:
- README.md
- background
- Makefile
# baseurl:
# highlighter: pygments
root_url: http://tgherzog.github.io/wbg-catalog-manual
markdown: kramdown
title: WBG Open Data Catalog Handbook
short_title: WBG Catalog

# project information
org_name: tgherzog
repo_name: wbg-catalog-manual
suggestion_branch: suggestions

# revision information
revision: 0.1
revdate: June, 2014
