exclude:
- README.md
- background
# baseurl:
# highlighter: pygments
root_url: http://tgherzog.github.io/wbg-catalog-manual
markdown: kramdown

# project information
org_name: tgherzog
repo_name: wbg-catalog-manual
suggestion_branch: suggestions

# revision information
revision: 0.1
revdate: June, 2014
